# Generated by Django 4.1.6 on 2023-02-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300, verbose_name='Имя гостя')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=3000, verbose_name='Текст записи')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('blocked', 'Заблокирована')], default='active', max_length=50, verbose_name='Статус записи')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата и время обновления')),
            ],
            options={
                'verbose_name': 'Гостевая книга',
            },
        ),
    ]
